name = "wynajem"
main = "src/index.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "wynajem-db"
database_id = "4eb9cfb1-df92-4482-b7bb-6c9e70ebae9a"

[vars]
ALLOWED_ORIGIN = "*"
